deploy-test-2:

    runs-on: ubuntu-latest

    needs: deploy-test-1

    steps:

      - uses: actions/checkout@v2

      - run: npm run setup tests/test-2/public_html/index.html

      - run: |

          git config --global user.email "mohamed@saoudi.tk"

          git config --global user.name "saoudimo"

          git add -A

          git commit -m "Added index.html"

      - uses: akhileshns/heroku-deploy@master

        with:

          heroku_api_key: ${{secrets.HEROKU_API_KEY}}

          heroku_app_name: "smohamed"

          heroku_email: "mohamed@saoudi.tk"

          appdir: "tests/test-2"

          buildpack: "https://github.com/heroku/heroku-buildpack-static.git"

          healthcheck: "https://akhileshns-hd-test-2.herokuapp.com/"

          delay: 5

      - run: npm run test-action https://smohamed.herokuapp.com/
